### ISSUE TITLE
Purpose of `core::convert::identity` in `include_unsafe`?

### ISSUE THREAD

**Issue by overlookmotel** [jmaargh/include_data#3]
I was looking at this crate for statically including typed data generated by [rkyv](https://rkyv.org/) (which does include padding).

Can I ask: What is the purpose of passing the transmuted bytes through `core::convert::identity` in `include_unsafe`?

https://github.com/jmaargh/include_data/blob/1bb2f69ddbf1d0b0572d36094970b3a75ab439e9/src/lib.rs#L169C14-L173

**Comment by jmaargh** [comment]
Good question - one that makes me wish I'd kept some notes from when I was writing this!

It sits in the same position as `typecheck` used in `include_data!`, which obviously has the effect of requiring the target type to implement `AnyBitPattern`. Clearly there are no such traits to check here, so that's not the reason. I think it might have something to do with requiring users to specify the type returned explicitly in some situations, but since (if it does do anything) I didn't include a test that fails if it's removed, I'm not sure right now. I'll think about it.

Just because your struct includes padding, doesn't mean that it doesn't fulfil the requirements of [`AnyBitPattern`](https://docs.rs/bytemuck/latest/bytemuck/trait.AnyBitPattern.html) though. You might still be able to use the `include_data!` macro. I see that the example is perhaps a bit misleading in this respect (and was written when I mistakenly thought that padding would be an issue when it's not) - a better example would be a struct that includes a `bool` member, which definitely does not satisfy `AnyBitPattern`.

**Comment by overlookmotel** [comment]
Thanks for coming back. Maybe it's to ensure that `T: Sized`?

The types I'm working with include `bool`s, `NonZeroU32` and enums, so plenty of types which don't satisfy `AnyBitPattern`. But anyway I'm looking for simple and fast, and to hell with safety! (not really, but I can ensure the validity of the data by other means)

I'm going to close this as, although the answer to my question is a bit unclear, you've at least not told me "we *have* to do this, because..."
